
#ifndef LIBPAS_ALR_H
#define LIBPAS_ALR_H

#define ACP_CMD_ALR_PROG_GET_DATA_RUNTIME 'q'
#define ACP_CMD_ALR_PROG_GET_DATA_INIT 'r'

#define ACP_CMD_ALR_PROG_SET_SMS 's'
#define ACP_CMD_ALR_PROG_SET_RING 't'
#define ACP_CMD_ALR_PROG_SET_GOAL 'u'
#define ACP_CMD_ALR_PROG_SET_DELTA 'w'

#define ACP_CMD_ALR_PROG_ENABLE 'x'
#define ACP_CMD_ALR_PROG_DISABLE 'y'
#define ACP_CMD_ALR_ALARM_DISABLE 'z'
#define ACP_CMD_ALR_ALARM_GET 'A'

#endif 

