#ifndef LIBPAS_ACP_CHANNEL_H
#define LIBPAS_ACP_CHANNEL_H

#define ACP_CMD_CHANNEL_STOP "psp"
#define ACP_CMD_CHANNEL_START "pst"
#define ACP_CMD_CHANNEL_RESET "prs"
#define ACP_CMD_CHANNEL_ENABLE "penl"
#define ACP_CMD_CHANNEL_DISABLE "pdsl"
#define ACP_CMD_CHANNEL_ADD "padd"
#define ACP_CMD_CHANNEL_DELETE "pdel"
#define ACP_CMD_CHANNEL_GET_DATA_RUNTIME "pgdr"
#define ACP_CMD_CHANNEL_GET_DATA_INIT "pgdi"
#define ACP_CMD_CHANNEL_GET_DATA "pgd"
#define ACP_CMD_CHANNEL_GET_ENABLED "pgenl"
#define ACP_CMD_CHANNEL_SET_SAVE "pssave"
#define ACP_CMD_CHANNEL_GET_ERROR "pgerr"

#endif

