
#ifndef LIBPAS_ACP_REGONF_H
#define LIBPAS_ACP_REGONF_H

#define ACP_CMD_REGONF_PROG_GET_DATA_RUNTIME 'q'
#define ACP_CMD_REGONF_PROG_GET_DATA_INIT 'r'

#define ACP_CMD_REGONF_PROG_SET_HEATER_POWER 's'
#define ACP_CMD_REGONF_PROG_SET_COOLER_POWER 't'

#define ACP_CMD_REGONF_PROG_SET_GOAL 'u'
#define ACP_CMD_REGONF_PROG_SET_HEATER_DELTA 'v'
#define ACP_CMD_REGONF_PROG_SET_COOLER_DELTA 'w'

#define ACP_CMD_REGONF_PROG_SET_CHANGE_GAP 'x'

#define ACP_CMD_REGONF_PROG_ENABLE 'y'
#define ACP_CMD_REGONF_PROG_DISABLE 'z'

#define ACP_CMD_REGONF_PROG_SET_EM_MODE 'A'

#endif 

