
#ifndef LIBPAS_ACP_REGSMP_H
#define LIBPAS_ACP_REGSMP_H

#define ACP_CMD_REGSMP_PROG_GET_DATA_RUNTIME 'q'
#define ACP_CMD_REGSMP_PROG_GET_DATA_INIT 'r'

#define ACP_CMD_REGSMP_PROG_SET_HEATER_POWER 's'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_POWER 't'

#define ACP_CMD_REGSMP_PROG_SET_GOAL 'u'
#define ACP_CMD_REGSMP_PROG_SET_CHANGE_GAP 'v'

#define ACP_CMD_REGSMP_PROG_SET_HEATER_MODE 'w'
#define ACP_CMD_REGSMP_PROG_SET_HEATER_DELTA 'x'
#define ACP_CMD_REGSMP_PROG_SET_HEATER_KP 'y'
#define ACP_CMD_REGSMP_PROG_SET_HEATER_KI 'z'
#define ACP_CMD_REGSMP_PROG_SET_HEATER_KD 'A'

#define ACP_CMD_REGSMP_PROG_SET_COOLER_MODE 'B'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_DELTA 'C'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_KP 'D'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_KI 'E'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_KD 'F'

#define ACP_CMD_REGSMP_PROG_ENABLE 'G'
#define ACP_CMD_REGSMP_PROG_DISABLE 'H'
#define ACP_CMD_REGSMP_PROG_SET_EM_MODE 'I'

#endif 

