
#ifndef LIBPAS_REGSMP_H
#define LIBPAS_REGSMP_H

#define ACP_CMD_REGSMP_PROG_GET_DATA_RUNTIME 'q'
#define ACP_CMD_REGSMP_PROG_GET_DATA_INIT 'r'

#define ACP_CMD_REGSMP_PROG_SET_HEATER_POWER 's'
#define ACP_CMD_REGSMP_PROG_SET_COOLER_POWER 't'
#define ACP_CMD_REGSMP_PROG_SWITCH_STATE 'v'

#endif 

